micronaut:
  application:
    name: throttling
  jpa:
    default:
      entity-scan:
        packages: 'com.nixsolutions.model'
      properties:
        hibernate:
          hbm2ddl:
            auto: none
          show_sql: true


datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://localhost:5432/throttling`}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    schema-generate: AUTO
    dialect: POSTGRES

liquibase:
  datasources:
    default:
      change-log: 'classpath:liquibase/liquibase-changelog.xml'